using System;
using System.Net;
using System.Text.RegularExpressions;
using Robust.Client;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.State;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.AuthLib;
using Robust.Shared.Configuration;
using Robust.Shared.ContentPack;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Log;
using Robust.Shared.Network;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.MainMenu;

[GenerateTypedNameReferences]
public sealed partial class MainMenu : UIScreen
{
    [Dependency] private readonly IGameController _game = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private ISawmill _sawmill = default!;
    public const string SawmillId = "interface.mainmenu";

    public MainMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SetAnchorPreset(this, LayoutPreset.Wide);

        SetAnchorPreset(MainMenuBox, LayoutPreset.TopLeft);
        SetMarginLeft(MainMenuBox, 25);
        SetMarginTop(MainMenuBox, 30);
        SetGrowHorizontal(MainMenuBox, GrowDirection.End);

        SetAnchorPreset(AboutBox, LayoutPreset.TopRight);
        SetMarginRight(AboutBox, -25);
        SetMarginTop(AboutBox, 30);
        SetGrowHorizontal(AboutBox, GrowDirection.Begin);

        Tittle.Text = _game.GameTitle();
        Username.Text = _cfg.GetCVar(CVars.PlayerName);
    }
}
